name: maatcontabil
region: nyc
features:
  - buildpack-stack=ubuntu-22

ingress:
  rules:
    - component:
        name: api
      match:
        path:
          prefix: /api
    - component:
        name: web
      match:
        path:
          prefix: /

services:
  - name: api
    environment_slug: node-js
    github:
      repo: gutembergferreira/MaatContabil
      branch: main
      deploy_on_push: true
    source_dir: maatcontabil_webhook
    http_port: 8080
    instance_size_slug: basic-xxs
    instance_count: 1
    build_command: npm ci
    run_command: npm start
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        value: ${DATABASE_URL}
        type: SECRET
      - key: DATABASE_SSLMODE
        value: require
      - key: SPACES_REGION
        value: ${SPACES_REGION}
      - key: SPACES_BUCKET
        value: ${SPACES_BUCKET}
      - key: SPACES_KEY
        value: ${SPACES_KEY}
        type: SECRET
      - key: SPACES_SECRET
        value: ${SPACES_SECRET}
        type: SECRET

static_sites:
  - name: web
    environment_slug: node-js
    github:
      repo: gutembergferreira/MaatContabil
      branch: main
      deploy_on_push: true
    source_dir: .
    build_command: npm ci && npm run build
    output_dir: dist
    catchall_document: index.html
    envs:
      - key: VITE_API_BASE_URL
        value: /api
